info:
  profile: dev

name: config-dev
words: this is a development environment  for update 2020-04-11
introduce: '{cipher}c4bf7b9427b3d72cfca3b47e72baae76f7f7b892833a532880b8104db8cecb07ea53e4be01ca482c055d217d57094642'


cattle: '{cipher}AQA2VqeVp1V+GJz3DBeSECfGuROqlQKVFI2YyD4u+l9WPk6lWYpA5RtTa2jzsUWW/4VFDoNdgTfmg8i6VmX1IPO5DXN6zXOhF11MaSPDkc8Wixr+3yo0U6FpiNOhD0nywkshsArR19SCKar1tagyoOjmj65YdVU5+aGlqtRoPd7+0xXxfZTy7zVvTYJIWjeglB7Vo3CqeTGX75GcL6AX9pLdLSQ11l54mR55Ga2uKjhW5oShxm05dkWqLcgx8IePTTbcsZE6L0DKe8ttUXlRw4w0wPNlwTbv9tAgZ69ISZIxDaoBSqSCDmpZ/YKK07Yo+dhnVeJiDfvzay7zWKhb478Q9+p7/nwRqxzl1xTg+ssO/8NpPe3GJb8ab44eVM1yEx/Tni/Tyu3LuYgdGS7JsMzw'
